import { NextResponse } from "next/server"
import { cookies } from "next/headers"

export async function POST(request: Request) {
  try {
    const { name, email, password } = await request.json()

    if (!name || !email || !password) {
      return NextResponse.json({ message: "Name, email, and password are required" }, { status: 400 })
    }

    // In a real app, you would:
    // 1. Check if the user already exists
    // 2. Hash the password
    // 3. Store the user in your database

    // Create a mock user for demo purposes
    const user = {
      id: "1", // This would be generated by your database
      name,
      email,
    }

    // In a real app, you would create a proper JWT token
    const token = "mock-jwt-token"

    // Set the session cookie
    cookies().set({
      name: "session",
      value: token,
      httpOnly: true,
      path: "/",
      secure: process.env.NODE_ENV === "production",
      maxAge: 60 * 60 * 24 * 7, // 1 week
    })

    return NextResponse.json({ user })
  } catch (error) {
    console.error("Registration error:", error)
    return NextResponse.json({ message: "Internal server error" }, { status: 500 })
  }
}
